version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug, Release
platform: x64
before_build:
- cmd: >-
    git submodule update --init --recursive

    mkdir build & cd build & cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_BUILD_TYPE="Release" ../
build:
  project: build/MAZEND_GAME.vcxproj
  verbosity: minimal
after_build:
- cmd: "cd %APPVEYOR_BUILD_FOLDER% \nset LOC=%APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/\nset ZIPNAME=mazend%CONFIGURATION%_%APPVEYOR_REPO_COMMIT%.zip\n7z a %ZIPNAME% %LOC%/*.exe %LOC%/*.dll %LOC%/res/* %LOC%/res/**/*"
artifacts:
- path: '*.zip'
  name: zip